use semver::Version;
use serde::Deserialize;
use std::collections::{HashMap, HashSet};
use std::env;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
struct BuildConfig {
    components: ComponentsSection,
}

#[derive(Deserialize)]
struct ComponentsSection {
    entry: Vec<ComponentEntry>,
}

#[derive(Deserialize)]
struct ComponentEntry {
    name: String,
    #[serde(rename = "crate")]
    crate_name: String,
    #[serde(rename = "struct")]
    struct_name: String,
    log_ignore: Option<Vec<String>>,
}

#[derive(Clone, Debug)]
struct DependencySpec {
    path: Option<String>,
}

fn main() {
    // set up
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let build_toml_path = Path::new(&manifest_dir).join("flowd.build.toml");
    println!("cargo:rerun-if-changed={}", build_toml_path.display());
    println!("cargo:rerun-if-changed={}", Path::new(&manifest_dir).join("build.rs").display());

    // load and validate build configuration
    let build_toml = fs::read_to_string(&build_toml_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", build_toml_path.display()));
    let config: BuildConfig = toml::from_str(&build_toml)
        .unwrap_or_else(|err| panic!("failed to parse flowd.build.toml: {err}"));

    if config.components.entry.is_empty() {
        panic!("flowd.build.toml has no component entries");
    }

    let root_cargo = load_root_cargo_toml(Path::new(&manifest_dir));
    let flowd_version = load_flowd_version(&root_cargo);
    let flowd_major_minor = (flowd_version.major, flowd_version.minor);
    let dependencies = load_dependency_specs(&root_cargo);

    let mut seen_names: HashSet<String> = HashSet::new();
    let mut log_filters: Vec<String> = Vec::new();

    for entry in &config.components.entry {
        if entry.name.trim().is_empty() {
            panic!("component entry has empty name");
        }
        if entry.crate_name.trim().is_empty() {
            panic!("component '{}' has empty crate name", entry.name);
        }
        if entry.struct_name.trim().is_empty() {
            panic!("component '{}' has empty struct name", entry.name);
        }
        if !seen_names.insert(entry.name.clone()) {
            panic!("duplicate component name '{}'", entry.name);
        }

        // check if it is present
        validate_crate_name(Path::new(&manifest_dir), &dependencies, &entry.crate_name);
        validate_component_version_compatibility(
            Path::new(&manifest_dir),
            &dependencies,
            &entry.crate_name,
            flowd_major_minor,
            &flowd_version,
        );

        // push log filter, if set
        if let Some(filters) = &entry.log_ignore {
            for filter in filters {
                if !log_filters.contains(filter) {
                    log_filters.push(filter.clone());
                }
            }
        }
    }

    // initialize generated code string
    let mut generated = String::new();
    generated.push_str("// @generated by build.rs; do not edit.\n\n");

    // use block
    for entry in &config.components.entry {
        //NOTE: cargo crate names use kebab case, but rustc uses snake case
        generated.push_str(&format!("use {}::{};\n", to_snake_case(&entry.crate_name), entry.struct_name));
    }
    generated.push_str("\n");

    // component library
    generated.push_str("pub(crate) fn build_component_library() -> Arc<RwLock<ComponentLibrary>> {\n");
    generated.push_str("    Arc::new(RwLock::new(ComponentLibrary::new(vec![\n");
    for entry in &config.components.entry {
        generated.push_str(&format!("        {}::get_metadata(),\n", entry.struct_name));
    }
    generated.push_str("    ])))\n");
    generated.push_str("}\n\n");

    // component factory function
    generated.push_str("pub(crate) fn instantiate_component(\n");
    generated.push_str("    name: &str,\n");
    generated.push_str("    inports: ProcessInports,\n");
    generated.push_str("    outports: ProcessOutports,\n");
    generated.push_str("    signalsource: ProcessSignalSource,\n");
    generated.push_str("    watchdog_signalsink: ProcessSignalSink,\n");
    generated.push_str("    graph_inout: GraphInportOutportHandle,\n");
    generated.push_str(") -> Option<Box<dyn RunnableComponent>> {\n");
    generated.push_str("    match name {\n");
    for entry in &config.components.entry {
        generated.push_str(&format!(
            "        \"{}\" => Some(Box::new({}::new(inports, outports, signalsource, watchdog_signalsink, graph_inout))),\n",
            escape_rust_string(&entry.name),
            entry.struct_name
        ));
    }
    generated.push_str("        _ => {\n");
    generated.push_str("            let _ = (inports, outports, signalsource, watchdog_signalsink, graph_inout);\n");
    generated.push_str("            None\n");
    generated.push_str("        }\n");
    generated.push_str("    }\n");
    generated.push_str("}\n\n");

    // component log filters function
    generated.push_str("pub fn register_component_log_filters(logger: &mut simplelog::ConfigBuilder) {\n");
    for filter in &log_filters {
        generated.push_str(&format!(
            "    logger.add_filter_ignore_str(\"{}\");\n",
            escape_rust_string(filter)
        ));
    }
    generated.push_str("}\n\n");

    // write generated code to file
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("build_generated.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn load_root_cargo_toml(manifest_dir: &Path) -> toml::Value {
    let cargo_toml_path = manifest_dir.join("Cargo.toml");
    let cargo_toml = fs::read_to_string(&cargo_toml_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", cargo_toml_path.display()));
    cargo_toml
        .parse()
        .unwrap_or_else(|err| panic!("failed to parse Cargo.toml: {err}"))
}

fn load_flowd_version(root_cargo: &toml::Value) -> Version {
    let raw = root_cargo
        .get("package")
        .and_then(|v| v.get("version"))
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("missing [package].version in root Cargo.toml"));
    Version::parse(raw).unwrap_or_else(|err| {
        panic!("invalid root Cargo.toml [package].version '{}': {err}", raw)
    })
}

fn load_dependency_specs(root_cargo: &toml::Value) -> HashMap<String, DependencySpec> {
    let mut specs = HashMap::new();
    if let Some(deps) = root_cargo.get("dependencies").and_then(|v| v.as_table()) {
        for (name, value) in deps {
            let path = value
                .as_table()
                .and_then(|t| t.get("path"))
                .and_then(|p| p.as_str())
                .map(str::to_owned);
            specs.insert(name.to_owned(), DependencySpec { path });
        }
    }
    specs
}

//TODO change to support components in separate crates (TO-BE) instead of modules (AS-IS), e.g. by checking for a Cargo.toml in the crate path and looking for a lib.rs or src/lib.rs file there, and also supporting nested modules in the components directory, e.g. components/ssh/mod.rs or components/ssh.rs for components::ssh
fn validate_crate_name(
    manifest_dir: &Path,
    dependencies: &HashMap<String, DependencySpec>,
    crate_name: &str,
) {
    if crate_name.starts_with("components::") {
        if !allow_module_components() {
            panic!(
                "module-based component '{}' is not allowed by default; enable with '--features allow-module-components'",
                crate_name
            );
        }
        let module = crate_name.trim_start_matches("components::");
        if module.is_empty() || module.contains("::") {
            panic!("invalid components module path '{}'", crate_name);
        }
        let components_dir = manifest_dir.join("src/components");
        let file_path = components_dir.join(format!("{module}.rs"));
        let dir_path = components_dir.join(module).join("mod.rs");
        if !file_path.exists() && !dir_path.exists() {
            panic!("components module '{}' not found in src/components", module);
        }
        return;
    }

    if crate_name.contains("::") {
        panic!("crate name '{}' is not a valid crate path", crate_name);
    }

    if !dependencies.contains_key(crate_name) {
        panic!("crate '{}' not found in Cargo.toml dependencies", crate_name);
    }
}

fn validate_component_version_compatibility(
    manifest_dir: &Path,
    dependencies: &HashMap<String, DependencySpec>,
    crate_name: &str,
    flowd_major_minor: (u64, u64),
    flowd_version: &Version,
) {
    if crate_name.starts_with("components::") {
        if !allow_module_components() {
            panic!(
                "module-based component '{}' is not allowed by default; enable with '--features allow-module-components'",
                crate_name
            );
        }
        return;
    }

    let dep = dependencies
        .get(crate_name)
        .unwrap_or_else(|| panic!("crate '{}' not found in dependency specs", crate_name));
    let dep_path = dep.path.as_ref().unwrap_or_else(|| {
        panic!(
            "crate '{}' has no local path in Cargo.toml; cannot validate version compatibility",
            crate_name
        )
    });

    let crate_cargo_toml_path = manifest_dir.join(dep_path).join("Cargo.toml");
    println!("cargo:rerun-if-changed={}", crate_cargo_toml_path.display());
    let crate_cargo_toml = fs::read_to_string(&crate_cargo_toml_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", crate_cargo_toml_path.display()));
    let crate_cargo: toml::Value = crate_cargo_toml.parse().unwrap_or_else(|err| {
        panic!(
            "failed to parse component Cargo.toml {}: {err}",
            crate_cargo_toml_path.display()
        )
    });
    let crate_version_raw = crate_cargo
        .get("package")
        .and_then(|v| v.get("version"))
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| {
            panic!(
                "missing [package].version in component Cargo.toml {}",
                crate_cargo_toml_path.display()
            )
        });
    let flowd_compat_raw = crate_cargo
        .get("package")
        .and_then(|v| v.get("metadata"))
        .and_then(|v| v.get("flowd"))
        .and_then(|v| v.get("compatible"))
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| {
            panic!(
                "missing [package.metadata.flowd].compatible in component Cargo.toml {}",
                crate_cargo_toml_path.display()
            )
        });
    let component_target_major_minor = parse_major_minor(flowd_compat_raw).unwrap_or_else(|| {
        panic!(
            "invalid [package.metadata.flowd].compatible '{}' in {} (expected at least major.minor, e.g. 0.4)",
            flowd_compat_raw,
            crate_cargo_toml_path.display()
        )
    });
    if component_target_major_minor != flowd_major_minor {
        panic!(
            "component '{}' version '{}' declares flowd compatibility {} but runtime is {}.{} ({})",
            crate_name,
            crate_version_raw,
            flowd_compat_raw,
            flowd_major_minor.0,
            flowd_major_minor.1,
            flowd_version
        );
    }
}

fn parse_major_minor(raw: &str) -> Option<(u64, u64)> {
    let mut parts = raw.split('.');
    let major = parts.next()?.parse::<u64>().ok()?;
    let minor = parts.next()?.parse::<u64>().ok()?;
    Some((major, minor))
}

fn allow_module_components() -> bool {
    env::var_os("CARGO_FEATURE_ALLOW_MODULE_COMPONENTS").is_some()
}

fn escape_rust_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\"', "\\\"")
}

fn to_snake_case(value: &String) -> String {
    return value.replace("-", "_");
}
